version: '3.1'

services:
  db:
    build: DockerFIle/mySQL
    container_name: mysql
    image: nobsxd/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - D:/volume/db:/var/lib/mysql


  phpmyadmin:
    build: DockerFIle/phpadmin
    image: nobsxd/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1


  rabbitmq:
    build: DockerFIle/rabbitMQ
    image: rabbitmq:3.11.0-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - D:/volume/rabbitmq:/var/lib/rabbitmq

    restart: unless-stopped
