package org.example.entity.enams.state;

public enum UserState {


	//---------------- Запуск бота
	BOT_START,
	BOT_CHANGE,

	//----------------Базовое состояние
	BASIC_STATE,

	//--------------- команды бота
	BOT_CANCEL,
	BOT_HELP,
	BOT_BACK,
	BOT_MAIN_MENU,
	INFO_SETTINGS,
	ADMIN,

	//--------------- акаунт
	ACCOUNT_LIST,
	ACCOUNT_SELECT,
	ACCOUNT_INFO,
	ACCOUNT_DELETE,

	//---------------- Добавление аккаунта
	ACCOUNT_ADD_REGISTER,
	ACCOUNT_ADD_NAME,
	ACCOUNT_ADD_PUBLIC_API,
	ACCOUNT_ADD_SECRET_API,
	
	//---------------- Трейдинг
	TRADE_MANAGER,
	TRADE_SETTINGS,
	TRADE_START,
	TRADE_STOP,
	TRADE_CANCEL,
	TRADE_OPERATION,
	TRADE_STATUS,

	//---------------- Найстройка трейдинга
	SETTINGS_NAME_PAIR,
	SETTINGS_SAVE_NAME_PAIR,
	SETTINGS_AMOUNT_ORDER,
	SETTINGS_SAVE_AMOUNT_ORDER,
	SETTINGS_STEP_BAY,
	SETTINGS_SAVE_STEP_BAY,
	SETTINGS_STEP_SELL,
	SETTINGS_SAVE_STEP_SELL,
	SETTINGS_DEPOSIT,
	SETTINGS_SAVE_DEPOSIT,
	SETTINGS_NAME_STRATEGY,
	SETTINGS_SAVE_NAME_STRATEGY,
	SETTINGS_ENABLE_DEMO_TRADING,
	SETTINGS_SAVE_ENABLE_DEMO_TRADING,

	//---------------- Меню администратора
	ADMIN_LIST_ALL_USERS,
	ADMIN_BAN_USER,
	ADMIN_UNBAN_USER,
	ADMIN_TRADING_STATS_ALL_USERS,
	ADMIN_TRADING_STATS_SPECIFIC_USER,
	ADMIN_STOP_TRADING_ALL_USERS,
	ADMIN_GRANT_ADMIN_RIGHTS,
	ADMIN_CANCEL_CACHE,


	BAN,
	U_BAN;

}
