currency:
  exchanges:
    binance:
      type: "binance"
      pairs:
        - namePair: "BTC-USDT"
          scale: 5

        - namePair: "BNB-USDT"
          scale: 3

        - namePair: "NOT-USDT"
          scale: 0

        - namePair: "SOL-USDT"
          scale: 3

        - namePair: "ETH-USDT"
          scale: 4
    bybit:
      type: "bybit"
      pairs:
        - namePair: "BTC-USDT"
          scale: 6

        - namePair: "BNB-USDT"
          scale: 5

        - namePair: "NOT-USDT"
          scale: 2

        - namePair: "SOL-USDT"
          scale: 3

        - namePair: "KAS-USDT"
          scale: 2