currency:
  exchanges:
    binance:
      type: "binance"
      pairs:
        - namePair: "BTC-USDT"
          scale: 5

        - namePair: "BNB-USDT"
          scale: 3
    bybit:
      type: "bybit"
      pairs:
        - namePair: "BTC-USDT"
          scale: 6