currency-binance:
  pairs:
    - "BTC-USDT"
    - "BNB-USDT"
    - "TRX-USDT"
    - "ETH-USDT"
    - "NOT-USDT"
currency-baybit:
  pairs:
    - "BTC-USDT"
    - "BNB-USDT"
    - "TRX-USDT"
    - "ETH-USDT"
    - "NOT-USDT"
currency-mexc:
  pairs:
    - "BTC-USDT"
    - "BNB-USDT"
    - "TRX-USDT"
    - "ETH-USDT"
    - "NOT-USDT"