name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запускать на пуш в ветку master

jobs:
  build:
    runs-on: ubuntu-latest  # Используйте последнюю доступную версию Ubuntu
    services:
      docker:
        image: docker:latest
        options: >-
          --mount type=bind,source=${{ github.workspace }},target=/workspace

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Проверка кода из репозитория

      - name: Set up JDK 17  # Убедитесь, что вы устанавливаете правильную версию JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'openjdk'
          java-version: '17'

      - uses: actions/checkout@v2
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
      - name: Run Docker Compose
        run: |
          cd /workspace
          docker-compose up

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew  # Установка прав на выполнение для gradlew

      - name: Set environment variables
        run: echo "SECRET_KEY_SALT=${{ secrets.SECRET_KEY_SALT }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.SHA }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and test
        run: |
          # Выполнение тестов с Gradle
          ./gradlew test || exit 1 
          
          # Сборка образа Docker
          docker-compose build

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose push  # Создание образа и публикация его в Docker Hub
